{% set name = "pixi-diff-to-markdown" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pixi_diff_to_markdown-{{ version }}.tar.gz
  sha256: 2896a45fc23111417329a9666ea78bff83129d658ea4b1a1b663efda0f0a16ce

build:
  entry_points:
    - pixi-diff-to-markdown = pixi_diff_to_markdown.__main__:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.12
    - hatchling
    - pip
  run:
    - python >=3.12
    - pydantic >=2.7.1,<3
    - py-rattler >=0.5.0,<0.6
    - ordered_enum >=0.0.8,<0.1
    - typer >=0.12.3,<0.13
    - pydantic-settings >=2.2.1,<3

test:
  imports:
    - pixi_diff_to_markdown
  commands:
    - pip check
    - pixi-diff-to-markdown --help
  requires:
    - pip

about:
  home: https://github.com/pavelzw/pixi-diff-to-markdown
  summary: Tool for converting `pixi update` diffs to markdown
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
